### ISSUE TITLE
Add npm package to the repo (link)

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/create-eth#52]
![image](https://github.com/scaffold-eth/create-eth/assets/2486142/48c91b89-a61e-4739-8668-bbc0dfdb02c1)

**Comment by technophile-04** [comment]
Been researching about it a bit and seems like the way to display the package on github UI is only through publish it to github packages, so we also need to publish the package to github registry i.e `registry=https://npm.pkg.github.com`. 

I was actually planning to add the action so that we publish to github packages but after reading for while not sure its worth it because if people need to install / use package via github registry they need to append org / user name in our case it would be `npx scaffold-eth/create-eth`. Checkout this [stackoverflow discussion](https://stackoverflow.com/questions/65493803/switching-from-npm-to-github-packages)

And event this [example](https://github.com/Codertocat/hello-world-npm/pkgs/npm/hello-world-npm) mentioned in [github packages](https://arc.net/l/quote/clmgfkcm) docs indeed also has forces you append user / org name before  package name. 

So I am not sure if its worth configuring because by doing this will also distribute the audience / numbers once using npm registry `npx create-eth@latest` and other will be fetching from `npx scaffold-eth/create-eth@latest`

**Comment by carletex** [comment]
Definitely not worth it! Thanks for looking into it @technophile-04
